### ISSUE TITLE
Change font to Arial in section 3

### ISSUE THREAD

**Issue by IgorWilbert** [publiclab/PublicLab.Editor#241]
### Please describe the problem (or idea)

To make a better looking and coherent format for the editor, I suggest changing the font of these lines to Arial:
![issue](https://user-images.githubusercontent.com/42987854/51419583-d4af7100-1b72-11e9-83ea-6154d738372b.JPG)

### Investigation
It is possible to solve it by just using a surrounding "font" tag like in `<font face="Arial">Your text here.</font>`. @jywarren if you agree, I'll turn this into a FTO issue. Thanks!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by rexagod** [comment]
Good find @IgorWilbert! Currently we use the styles `font-family: "Helvetica Neue",Helvetica,Arial,sans-serif;` with these respective fallbacks. It'd be nice to specify this whole combination instead of the individual `Arial` font, and please do submit a PR while you're at it so we can have a look. Thanks!
