### ISSUE TITLE
Refactor tagname/username/emoji autocompletion using atwho library

### ISSUE THREAD

**Issue by jywarren** [publiclab/PublicLab.Editor#44]
Autocompletion with `horsey` is just not working reliably in this library. But @cheneyshreve and @ViditChitkara have implemented some amazing autocompletion on the plots2 project using the atwho library:

* https://github.com/ichord/At.js/ (underlying atwho, pure JS)
* https://github.com/publiclab/plots2/pull/2925 (reference implementation on plots2)

@cheneyshreve has documented the at.js lib [working in concert with our Woofmark rich text editor](https://github.com/publiclab/plots2/pull/2925#issuecomment-401438594) module. So this should work! We'd love some help getting this up and running.

**Comment by cheneyshreve** [comment]
Hi @jywarren yes, I'd love to work on this. I got a start moving the atwho emoji code into app/assets/javascript and working on generalizing that code for use in other editors with a couple follow-up questions, but haven't gotten those organized quite yet (traveling today). Where's the best place to reach out with questions/ideas?

**Comment by jywarren** [comment]
back in the issues you opened for them would be fine! Thanks! And no rush,
just making a space for this to happen :-)

Safe travels!

**Comment by cheneyshreve** [comment]
Hi @jywarren I'm installing the npm package associated with [atwho](https://www.npmjs.com/package/at-mc/v/1.6.3) using
$ npm i at-mc --save-prod

which updates the dependencies as expected. Should I run npm audit fix to address vulnerabilities found or could this potentially cause problems? It doesn't mention this kind of side-effect on the npm blog but wanted to double-check since the audit is only npm 6 and higher.

**Comment by jywarren** [comment]
I am tending to think we should run the audit on old packages in a separate
PR, but on newly added packages in the PR where they're introduced.

But be sure things all still pass tests after doing the audit fix!

**Comment by cheneyshreve** [comment]
thanks @jywarren will do!

**Comment by cheneyshreve** [comment]
I just checked test.html and there are errors;  I wasn't sure if they were introduced from the npm audit fix so I cloned the repo and set it up in a different directory (I did not get the same errors setting up this time w.r.t. moment after the new changes you made), but same Jasmine test errors as my repo where I did  run npm audit. 

The errors relate to files not loading, not sure why yet because the files are there so it should be easy to resolve and unrelated to npm audit.
```
Error: Fixture could not be loaded: spec/javascripts/fixtures/index.html (status: error, message: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'file:///Users/cheneyshreve/PublicLab.Editor/spec/javascripts/fixtures/index.html?_=1533864591354'.)

etc.
```
A general question regarding the autocomplete edits, am I on the right tracking thinking I should edit the /adapters/PublicLab.Woofmark.js file by requiring the atwho library and editing the _module.options.tags, _module.options.authors (and adding a _module.options.emoji) or do the edits need to be made elsewhere in the modules? Thanks for all your help on this.

**Comment by jywarren** [comment]
Hi, I think if tests pass on the command line (npm test I think?) we can
address the browser based testing in another issue, thanks!

It'll either be in the woofmark file OR in modules/....RichTextModule.js --
I think the latter. There should be previous code attempting to do this...
using the horsey library. You can remove this!

Thanks!! Sounds like you're off to a great start!

**Comment by cheneyshreve** [comment]
Hi @jywarren, I have a couple questions on this when you have a chance:
so far I have:
- installed atwho and carat.js(dependency) using node & updated index.html
- experimented with commenting out portions of the PublicLab.Woofmark.js to understand (better) how the current autocompletes are working. 
- started editing PublicLab.RichTextModule.js to try to incorporate atwho by requiring it, hard-coding (at first) a configuration for hashtag autocomplete, and calling atwho on _module.textarea.

Question 1: It's not clear to me where in this code I should be making the atwho calls, or the proper syntax regarding accessing the textarea component, e.g.:

```
module.exports = PublicLab.RichTextModule = PublicLab.Module.extend({

  init: function(_editor, options) {

    var _module = this;
    
    .....
    
      _module._super(_editor, _module.options);
 
    
    var tagdata = ["hello", "world"];
    var hashtags_config = {
      at: "#",
      data: tagdata,
      displayTpl: "<li>${name}</li>"
    };
  
    $(_module.textarea).atwho(hashtags_config);
 ```
 
   Generates this output in the rich text editor:

```{atwho}${name}```

  Looking back at the PublicLab.Woofmark.js, the predefined hashtags for the horsey method are actually prefaced with a hash, so I tried that too, e.g. ["#hello", "#world"] but same result. 
  
 I'm not certain what this output from (atwho) means; if it's that atwho is called and there a loss of the input text somewhere along the way (e.g. maybe I need to edit the PublicLab.Woofmark.js where it's parsing and where it's defining _module.options.tags, _module.options.authors?) but maybe not because atwho is already rendering something probably not reliant on that code.
  
Question 2: Next question relates to using PublicLab api to narrow down results versus hard-coded version above. I'm unsure of the approprite address to use for the post? In plots2, we were using '/tags/suggested/'. Will we need to have a header and a token and use https://publiclab.org/tags/suggested and/or is there a way to do this using localhost? I haven't pushed anything on this PR yet but can push up code if you like. Thanks for all your help with this!

**Comment by jywarren** [comment]
Question 2 first (and apologies as I'm traveling the next 10 days so i'm a bit slower to reply) --

You shouldn't need a token to hit `/tags/suggested` but your idea of doing this on localhost is good -- consider requesting and saving a typical output from publiclab.org and then storing it as a static file at `http://localhost.../tags/suggested` so you can run this against a static file and not complicate things?

For Q1, I wonder if it is taking your input to the textarea and translating and copying that over to the rich text area... and there's some mixup happening there. Could you open a PR with your code so far so I can take a look? 

For reference, the sections with the `horsey` implementation are here:

https://github.com/publiclab/PublicLab.Editor/blob/cb7c7e19611afe16cb1aed8ff45273bf098a6320/src/adapters/PublicLab.Woofmark.js#L243-L284

notice how we made them disable-able, really because they were buggy. I think you could use the same `_module.options.authorsAutocomplete` to make them enable/disabale-able with the `atwho` implementation, too. 

See if you can get it working consistently in markdown mode first, and we'll look at the whole PR, then identify what's going wrong in the rich text mode next. I think there are two approaches -- first, trying to ensure that the Woofmark system properly translates what `atwho` puts into the textarea, or second, actually turning off `atwho` for the textarea when you're in rich text (`wysiwyg`) mode, and instead trying to run `atwho` directly on the `wysiwyg` element instead of on the textarea when it's in that mode.

**Comment by jywarren** [comment]
no problem - just got back from travel and happy to plug in again when
you're available!

**Comment by jywarren** [comment]
Hi @cheneyshreve -- no worries if you've gotten busy with other things but just wanted to see if you were still interested in working on this!

**Comment by rexagod** [comment]
Will be implemented later on in the 'React' patch with [zurb support](https://github.com/BolsteDev/react-tribute)(since atwho isn't maintained any more)

**Comment by jywarren** [comment]
Hi, I think doing it in zurb is OK if it will work (`at` has been demonstrated to work) but I would prefer to solve this more narrowly and modularly rather than tie it to the React project. I hope this makes sense. 

I have a slight preference for trying to solve it with `at` right now because that's what we have deployed already on `plots2`, so the integration code would be identical -- more maintainable!

**Comment by geekychaser** [comment]
@jywarren  I also had the thought of refactoring tagname using 
 [zurb/tribute]https://github.com/zurb/tribute) as [at.js](https://github.com/ichord/At.js/#announcement) is no longer being maintained. And using a project which is no longer being maintained can lead to maintenance and reliability issues in future. 
But I see a PR has been already been opened by @rexagod 

Also I am not able to understand which react project are you refering to?

Thank you
