### ISSUE TITLE
make button/link styles more consistent and clearly "pressable"

### ISSUE THREAD

**Issue by jywarren** [publiclab/PublicLab.Editor#443]
Lots of different links and buttons are not styled to indicate they are interactive. (related to #409 and https://github.com/publiclab/PublicLab.Editor/issues/346)

For example, `1 entries` is actually a link expanding a list of revisions:

![image](https://user-images.githubusercontent.com/24359/78041869-440c1d80-733f-11ea-848b-6bb5b84cadd3.png)

There are other places (#346) where css styling consistency will help these make more sense. We'd love help tweaking underlines, button styles across the library, one at a time!

**Comment by keshav234156** [comment]
I think this happens due to inconsistencies between https://github.com/publiclab/PublicLab.Editor/blob/master/examples/index.html and https://github.com/publiclab/plots2/blob/master/app/views/editor/rich.html.erb .If we see https://publiclab.github.io/PublicLab.Editor/examples/ then it works perfectly fine.

![Screenshot from 2020-03-31 20-45-02](https://user-images.githubusercontent.com/45951376/78043101-8c9ff700-7390-11ea-83bc-be88998f6247.png)

what are your thoughts?

**Comment by keshav234156** [comment]
We should make https://github.com/publiclab/plots2/blob/master/app/views/editor/rich.html.erb  consist with https://github.com/publiclab/PublicLab.Editor/blob/master/examples/index.html

**Comment by Shulammite-Aso** [comment]
Yeah @keshav234156 i noticed https://github.com/publiclab/PublicLab.Editor/blob/master/examples/index.html more of the desired stylings than what is actually served on publiclab/post.  
Only i don't seem to understand yet why the different exists. I used to think https://publiclab.org/post serves exactly what is on https://github.com/publiclab/PublicLab.Editor

 There seem to me to be some custom css on example.html that is not being seen by publiclab/post, is this true? Because i don't see any actually.

And if there are some style rules that publiclab/post is not seeing, how do we inject them into it? Declear those styles in the modules and publiclab.History.js?
@jywarren i'ld appreciate some help wrapping my head around this better.

**Comment by VladimirMikulic** [comment]
@Shulammite-Aso the styles are stored in our CMS `plots2` under `app/assets`.
