### ISSUE TITLE
Weekly Community Check-In #61 - Bash aliases

### ISSUE THREAD

**Issue by cesswairimu** [publiclab/PublicLab.Editor#523]
Hi everyone! 👏
Hope everyone is safe :heart: 

We all at Public Lab 🎈 - learn, grow, work, brainstorm ideas, contribute together so why not share about our weekly goals and the awesome work we have done at Public Lab with each other, so we can support and collaborate with each other better. We have a Community Check-In each week, where every community member can share something about their work from the past week and about their current week's goal 🎯 . You are also welcome to share fun-fact 😄 , new ideas 💡 , your learning goals ☑️.

We believe in collaborative efforts to support our community. We are running a learning platform which helps a newcomer to become master of tomorrow. 💯

## Bash Aliases
Let make it fun this week and share your regular bash aliases that are a must have every time you setup a new PC
Let us know what you will be working on this week and if blocked express it below so that you can get help

 ### To Outreachy and GSoc Interns !Important
This is the official first week of SOC. We normally have the interns outline what they will be working on this week on the check-in. So kindly do so..if for some reason you will be away during the week this is also a good place to let the mentors know. Remember to be kind to yourself as it can get overwhelming during the first weeks..break out features into small issues and solve them incrementally. In case of any questions  ping respective mentors and they will get back as soon as possible. 
As usual if any blogs please drop the links. Happy coding :balloon: 

### To mentors
Please be on the lookout for concerns/questions and reviews that the interns so that we can keep the programs running smoothly. Thanks

### Reviewers and fellow contributors
We would love your help reviewing the interns PRs as they start coming in and also would appreciate chip-ins on discussions on various issues..Let do what we do best...collaborating :balloon: 

## Next Check-in
If you would like to open the next check-in..Leave a comment below. We are happy to help if its your first time
**Also challenging every intern this summer to make sure you have opened at least 1 check-in** :sweat_smile:  

Thanks everyone and have a great week 🎈

**Comment by cesswairimu** [comment]
@keshavsethi, @jywarren, @AyanChoudhary, @imajit,@NitinBhasneria, @nstjean, @marientje, @rutger-t, @Janet33, @TroydonAnabolic, @priyanshbalyan, @Medlineme4, @mandysGit, @msanden, @AidenOliver, @Janetsomehow, @AntroMarina, @llabake, @khushi02, @Alexjake660, @LarrySul, @nicoleiocana, @chrisdrums1, @Angelvicks, @Akanksha1212, @beladinaelfitri, @rid1hady, @shreyaa-s, @goamoth, @SusannaDiV, @yusofsf, @nanlliu, @Tlazypanda, @keshav234156, @WaldenJosh, @B4Lee, @VisnuGanth, @jessibreen, @alaxalves, @kamal-kaur04, @sssash18, @chinmay021, @Srija616, @AnnaMinakova, @greenbrown, @taysa91, @TaishiRoy, @yagmurbaydogan, @Shulammite-Aso, @Jigyasa-Kumari, @moliver4, @justinelai, @Snouzy, @stevenalila, @Digiox, @yandu31, @milosv1, @jamescapps, @Nevenem, @chirag-wadhwa, @yogeshjdeshmukh, @omizrahi99, @cesswairimu, @theOpetunde, @sailahonkanen, @robin-natale, @avidler, @ccyccyccy

**Comment by cesswairimu** [comment]
@moliver4, @justinelai, @Snouzy, @stevenalila, @Digiox, @yandu31, @milosv1, @jamescapps, @Nevenem, @chirag-wadhwa, @yogeshjdeshmukh, @omizrahi99, @theOpetunde, @sailahonkanen, @robin-natale, @avidler, @ccyccyccy
@urvashigupta7, @daemon1024, @Tlazypanda, @jscastanos, @sarthak-choudhary, @dongskyler, @keshavsethi, @Shulammite-Aso, @ckchu8, @keshav234156, @DerekChristy, @Srija616, @priyanka-choubey, @AyanChoudhary, @imajit, @NitinBhasneria, @nstjean, @marientje, @rutger-t, @Janet33, @TroydonAnabolic, @priyanshbalyan, @Medlineme4, @mandysGit, @msanden, @AidenOliver, @Janetsomehow, @AntroMarina, @llabake, @khushi02, @Alexjake660, @LarrySul, @nicoleiocana, @chrisdrums1, @Angelvicks, @Akanksha1212, @beladinaelfitri, @rid1hady, @shreyaa-s, @goamoth, @SusannaDiV, @yusofsf, @nanlliu, @WaldenJosh, @B4Lee, @VisnuGanth, @jessibreen, @alaxalves, @kamal-kaur04

**Comment by Tlazypanda** [comment]
Hey everyone 👋 might not be able to connect for a day or 2 since we have an incoming cyclone here in Mumbai

**Comment by jywarren** [comment]
Hi all, be safe @Tlazypanda and others facing storms (there was also a major storm in El Salvador the past weekend) sending ❤️ to all!!

I wanted to especially commend @Tlazypanda for so thoroughly and kindly welcoming a newcomer with installation support in https://github.com/publiclab/plots2/issues/7817#issuecomment-635454757 -- thank you so much!

Things in the US are very troubling right now and so also sending ❤️ and ✊ to those joining protests -- be safe!

**Comment by gr455** [comment]
Hi Everyone! Hope you guys are doing well. Be safe @Tlazypanda . I am about 150 kilometres away from Mumbai so am relatively safer from the cyclone but might still face a nudge from it.

Coming to the theme, I have recently started using 'doc' for docker-compose, since I have been using a lot of docker and docker-compose lately. One of my friends has 'please' for sudo which is quite funny.

For the past week, I have been helping develop an application to keep track of events happening around for the university, so I'll be doing that this week too. Along with that, will keep helping with the coverage on spectral-workbench.

**Comment by keshavsethi** [comment]
Hey everyone, Hope you all are fine:mask: and doing well. :heart: Last week I worked on some of the features of Spam management Dashboard. I made an alternate Url  /spam2 for better review and understanding. Most fo bulk moderation features are done and I have also added new filters in datatable for better moderation. Some of the tests are also done. You can find it at https://github.com/publiclab/plots2/pull/7969 (please review). Thanks to @VladimirMikulic @cesswairimu @jywarren @Uzay-G @pydevsg @ananyaarun for all the reviews and suggestions :smile:.  @Tlazypanda and @jywarren be safe :heart:

**Comment by NitinBhasneria** [comment]
Hey everyone, I hope you're having a great week. 
In the last week I was not able to use my laptop due to few things. Well, I am fine now and being active past 2-3 days. In the past days I have improved the drag and drop CSS popup. The problem of location spinner is totally solved thanks to @VladimirMikulic for his work and great reviews❤️. 
Thank you everyone and be safe @Tlazypanda😇.

**Comment by alaxalves** [comment]
Hey guys,
For this week I had Ruturaj's help on the Spectral Workbench upgrades, we've been incresing the test coverage here:
- https://github.com/publiclab/spectral-workbench/pull/513
- https://github.com/publiclab/spectral-workbench/pull/514

I have also setup Mapknitter's Dockerfile for production env guided by Sebastian's suggestion here (which actually I need to be reviewed): 
- https://github.com/publiclab/mapknitter/pull/1329

And also I have started an effort on setting system tests for Spectral Workbench at:  https://github.com/publiclab/spectral-workbench/tree/feat/system-tests but I'll focus on getting https://github.com/publiclab/spectral-workbench/pull/499 merged now, since Jeff has given me some guidance on the upcoming steps.

Hope everyone is safe!! <3

**Comment by shreyaa-s** [comment]
Hey everyone!
Hoping for everyone's safety. :heart: 
Take care @Tlazypanda and everyone else going through a tough time :heart: 

For this week my main goal is to understand how `domador` and `megamark` work, and learn to deal with the issues in parsing. Alongside, I'll try to review wherever I could and pick up another issue. Here's last week's work: #521 .
Right now, I'm swamped with college assignments and juggling deadlines. I'll get back on track as soon as I get some of it done.

**Comment by keshav234156** [comment]
Hi everyone
Hope everyone is fine. 
This week I am working on #519.This will and add the linting tool to the project  and will work to Improving on https://github.com/jywarren/woofmark/pull/1

**Comment by Shulammite-Aso** [comment]
Sending you love❤ @Tlazypanda and @gr455 stay safe. 

So far this week, I have worked on the toolbar stickness issue #394 and have made PR at #522 

The fix in the PR is just one of the many ways to possibly make using the toolbar less stressful for people making any kind of posts with the editor.   I think maybe if anybody could look at @jywarren comment here https://github.com/publiclab/PublicLab.Editor/issues/394#issuecomment-637772976 to see the reports from people concerning the toolbar and suggestions on how to possibly fix the problem, they could send In their thoughts as a review on #522.  That would be appreciated. 😀

Also,  I have not shared link to my first outreachy blog post with the community, sorry about that 🤗 and here it is
https://shulammiteaso.wordpress.com/2020/05/22/my-experience-applying-into-outreachy-internship/ 😀

**Comment by ebarry** [comment]
Thanks @cesswairimu for opening up this check-in, and to all 7 Outreachy and GSoC Fellows for writing in: @Shulammite-Aso @shreyaa-s @NitinBhasneria @keshav234156 @alaxalves @keshavsethi @Tlazypanda 💫 Good to hear that people are hanging in, finding their ways through, and contributing some stellar insight and code. 

I want to appreciate the collaborative effort that went into fixing the Tag Subscription page https://publiclab.org/stats/subscriptions in https://github.com/publiclab/plots2/issues/7908 ! Just went live this AM!

Next up, what i'm seeing as the top priorities from the Public Lab user community (besides, of course, the big summer-long Outreachy and GSoC projects 💚) are:

- This issue about search by @kgradow1 https://github.com/publiclab/plots2/issues/7973 - i'm writing in something now. 
- Fixing the display on contributor pages: https://github.com/publiclab/plots2/issues/7817 (thanks for help on this @sanchibansal340, @patcon, and @Tlazypanda 

Check out this fun FTO-candidate issue: the week before last, we had an incredible person in France translate nearly our entire site into French by following the process laid out by @gauravano a couple years ago on http://publiclab.org/translation (🌍🌏🌎 thank you!). This translator pointed out that the alert shown when someone is about to delete a wiki page is inadequate, and went on to write us a new one! Here it is, ready to be added into the code thanks to code links from @jywarren. I'm hoping someone could format this up a little better to enable a First Timer to take it on? https://github.com/publiclab/plots2/issues/7959

**Comment by ebarry** [comment]
One more question, as more and more people globally are connecting online, what mode of connection is working best for you with people in your region, and with people who may be far away geographically? Phones or internet? Jitsi, Skype, Zoom, Big Blue Button, Discourse voice channel, other? All input into this will be helpful as the first two calls we've attempted with the 7 GSoC and Outreachy Fellows and with the subset of 4 Fellows who are working on the Editor this year were troubled by irregular connectivity, and we'd like to know what platform is working better for people in which areas before setting up our usual Summertime All Code Community call. Thank you!

**Comment by emilyashley** [comment]
Hello everyone! Hope everyone is doing well and being kind to themselves. Things are not "normal" right now but we're all trying :)

I've been taking a look at the way we post on Public Lab this week (and even wrote my very first Public Lab Community [Question!](https://publiclab.org/questions/emash/06-01-2020/how-do-you-write-and-post-in-the-public-lab-community-asking-for-our-developers)) 

Starting up a feature inventory and feature parity google doc because there's so many features and possible bugs that I'm unfamiliar with. 

As for bash aliases, one of the first things I did when I was learning aliases was to have my terminal say `You're welcome` when I entered `Thank you.` Also, aliased `sudo` as `prettyplease` 💖Polite computing!

**Comment by cesswairimu** [comment]
Thanks all for all you sharing..I am def adding a kind alias for my "sudo" :smile: 
I have gbr- git branch, gci-git commit, v-vim

I am looking for someone with knows Greek to help review this awesome greek translation [PR](https://github.com/publiclab/plots2/pull/7981) by @ioampatzidis

**Comment by patcon** [comment]
Oh! I really love `alias prettyplease=sudo`! I'm def adding one for `pls` :)

**Comment by patcon** [comment]
Oh! Speaking of CLI aliases, when I used to work at a company with lots of hilarious coworkers, we'd often say off-hand that we wished we had some one-liners on tshirts. So I wrote a script called `tshirt` that I could "pipe into" in order to immediately order a custom tshirt emblazoned with text and have it mailed to the office (from zazzle or cafe press)

```
echo why did you want the internet in your shoes? | tshirt

**Comment by cesswairimu** [comment]
Moved to https://github.com/publiclab/plots2/issues/8002. Thanks everyone
