### ISSUE TITLE
Weekly Community Check-In #69 - Share your free time hobbies

### ISSUE THREAD

**Issue by sagarpreet-chadha** [publiclab/PublicLab.Editor#578]
Hi everybody! 👏

We all at Public Lab 🎈 - learn, grow, work, brainstorm ideas, contribute together so why not share about our weekly goals and the awesome work we have done at Public Lab with each other, so we can support and collaborate with each other better. We have a Community Check-In each week, where every community member can share something about their work from the past week and about their current week's goal 🎯 . You are also welcome to share fun-fact 😄 , new ideas 💡 , your learning goals ☑️.

We believe in collaborative efforts to support our community. We are running a learning platform which helps a newcomer to become a leader of tomorrow. 💯

## Share your hobbies apart from coding 💯 

Hey everyone :wave: 
This week let's share the activities you do when not coding, how do you spent time? Movies, singing, exercises, etc? 
🏃‍♂️ 🧑‍🎤 🎥 

### Thank you note to focus issues contributors

**A huge shoutout to PublicLab interns this summer for doing amazing job so far** 🎉 

## For the Interns
If you are blocked on something, please leave a comment and we will be sure to help. For the interns if you have any blogs please leave a link below and we will check them out.

## For the mentors
Please be on the lookout for concerns/questions and reviews that the interns so that we can keep the programs running smoothly. Thanks :v: 

## Next Check-in
If you would like to open the next check-in..Leave a comment below. We are happy to help if its your first time

**Thanks everyone for making Public Lab awesome** 🎈
Have a great week and year ahead all ❤️

**Comment by sagarpreet-chadha** [comment]
@JapneetSingh5, @Neilblaze, @markkulube, @vinuch, @Tlazypanda, @icarito, @dependabot-preview[bot], @jywarren, @keshavsethi, @praaatik, @Janitham97, @imanishbarnwal, @dburugupalli, @adityakpranav, @ioampatzidis, @esiebomaj, @Alexjake660, @cesswairimu, @urvashigupta7, @daemon1024, @jscastanos @keshavsethi, @jywarren, @AyanChoudhary, @imajit,@NitinBhasneria, @nstjean, @marientje, @rutger-t, @Janet33, @TroydonAnabolic, @priyanshbalyan, @Medlineme4, @mandysGit, @msanden, @AidenOliver, @Janetsomehow, @AntroMarina, @llabake, @khushi02, @Alexjake660, @LarrySul, @nicoleiocana, @chrisdrums1, @Angelvicks, @Akanksha1212, @beladinaelfitri, @rid1hady, @shreyaa-s, @goamoth, @SusannaDiV, @yusofsf, @nanlliu, @Tlazypanda,

**Comment by sagarpreet-chadha** [comment]
@keshav234156, @WaldenJosh, @B4Lee, @VisnuGanth, @jessibreen, @alaxalves, @kamal-kaur04, @sssash18, @chinmay021, @Srija616, @AnnaMinakova, @greenbrown, @taysa91, @TaishiRoy, @yagmurbaydogan, @Shulammite-Aso, @Jigyasa-Kumari @moliver4, @justinelai, @Snouzy, @stevenalila, @Digiox, @yandu31, @milosv1, @jamescapps, @Nevenem, @chirag-wadhwa, @yogeshjdeshmukh, @omizrahi99, @theOpetunde, @sailahonkanen, @robin-natale, @avidler, @ccyccyccy
@urvashigupta7, @daemon1024, @Tlazypanda, @jscastanos, @sarthak-choudhary, @dongskyler, @keshavsethi, @Shulammite-Aso, @ckchu8, @keshav234156, @DerekChristy, @Srija616, @priyanka-choubey, @AyanChoudhary, @imajit, @NitinBhasneria, @nstjean, @marientje, @rutger-t,

**Comment by sagarpreet-chadha** [comment]
@Janet33, @TroydonAnabolic, @priyanshbalyan, @Medlineme4, @mandysGit, @msanden, @AidenOliver, @Janetsomehow, @AntroMarina, @llabake, @khushi02, @Alexjake660, @LarrySul, @nicoleiocana, @chrisdrums1, @Angelvicks, @Akanksha1212, @beladinaelfitri, @rid1hady, @shreyaa-s, @goamoth, @SusannaDiV, @yusofsf, @nanlliu, @WaldenJosh, @B4Lee, @VisnuGanth, @jessibreen, @alaxalves, @kamal-kaur04 @adityakpranav @esiebomaj @Yonttee @swarajpure @vinuch @ishika1727 @nsachin08 @Rohit-786 @daemon1024

**Comment by ebarry** [comment]
Fun check-in prompt @sagarpreet-chadha ! My hobbies now are less than before, mostly I just grow plants, but when times are more ordinary I like reading science fiction, dancing, and making silly puns. 🙂

**Comment by Tlazypanda** [comment]
Thanks @sagarpreet-chadha for opening the check-in :tada:  I have with the whole-stay-at-home situation started reading books a lot which used to be one of my fav things when I was a kid :joy: 

I have also started learning spanish on Duolingo because I literally find the language really captivating and interesting _(interesante_ xD) maybe @alaxalves you can teach me something  :stuck_out_tongue: 

This week I focused on finding out some of the n+1 queries in the website and some other ways in which we can speed up our performance. I have also been improving on the Print template (with guidance from @ebarry Thanks!!) 

@jywarren @cesswairimu I have to mention that my college classes will be starting from the 30th July so my availability might be a bit less but not less than what Outreachy expects out of us :sweat_smile: And most certainly I will try to make the most of it :smile:

**Comment by cesswairimu** [comment]
Hello all :wave: 
My hobbies are dancing, singing along to music(I really can't sing though, sounds like I am talking :smiley: ) and  solving puzzles.
Great check-in @sagarpreet-chadha  :tada:  and  thanks for the heads up @Tlazypanda

**Comment by jywarren** [comment]
Hi all! My hobby is pixel art! 

![Screen Shot 2020-05-21 at 1 14 40 PM](https://user-images.githubusercontent.com/24359/88853675-15ebfc80-d1be-11ea-9c0d-b8c8c1489e6e.png)

Thanks for a great theme, @sagarpreet-chadha 😂 

@Tlazypanda no problem, and thank you! Outreachy has especially noted that due to the global crisis we will be extra flexible this year. Take care of yourself! And, I speak Spanish so feel free to leave your commit messages in spanish 😂 ! 

If anyone wants to practice Russian with me that's appreciated! Я нужно писатъ на практике! (i hope that was pretty close) 

@cesswairimu do you ever do these puzzles from the Guardian? https://www.theguardian.com/science/series/alex-bellos-monday-puzzle pretty tough sometimes and real fun!

**Comment by cesswairimu** [comment]
Wow, @jywarren nope, I've never came across them... really excited to try them out... thanks 😊

**Comment by Shulammite-Aso** [comment]
Hi all!🙋

I love taking documentary pictures and also love to watch short sci-fi movies on YouTube, or any other quick/short interesting movies. I don't like to follow movies with a lot of series.😆

Also remembering that I have not showed up on the weekly check-in for a few weeks now. 

Usually want to look up some other notifications first then come back to the check-in later, but before you know it the next check-in is here. 🙈

Will try to show up more often.

**Comment by shreyaa-sharmaa** [comment]
Hey everyone!
Nowadays I'm learning to play guitar! Other than that, I love to read. 
Here's the link to my blog: https://shreyaa-sharmaa.github.io/outreachy-blog/
Thanks!

**Comment by cesswairimu** [comment]
Hi :wave: Anyone wonna open this week's check-in?

**Comment by sagarpreet-chadha** [comment]
Anyone from PL editor team wants to volunteer to open the check in today?
@NitinBhasneria @keshav234156 @shreyaa-sharmaa @Shulammite-Aso , maybe @Tlazypanda  can do again?

🎈 😄

**Comment by Shulammite-Aso** [comment]
Let me do this @sagarpreet-chadha 😆

**Comment by Shulammite-Aso** [comment]
@sagarpreet-chadha @cesswairimu will I have to do it at the editor repo?

**Comment by Shulammite-Aso** [comment]
Hi @sagarpreet-chadha @cesswairimu here is the new check-in https://github.com/publiclab/PublicLab.Editor/issues/585
Only need some help tagging everyone now.😄

Thanks!!!

**Comment by cesswairimu** [comment]
Thanks so much @Shulammite-Aso 🎉🎉...will do the tagging no prob...and I didn't see the msg in time...we can do check-ins in any of the repos. Thanks

**Comment by sagarpreet-chadha** [comment]
Thanks so much @Shulammite-Aso 🎉🎉

**Comment by cesswairimu** [comment]
Moved to https://github.com/publiclab/PublicLab.Editor/issues/585 Thanks all
