### ISSUE TITLE
Weekly Community Check-In #70 - Share your adventures for the next few weeks and months

### ISSUE THREAD

**Issue by Shulammite-Aso** [publiclab/PublicLab.Editor#585]
Hi everybody! 👏

We all at Public Lab 🎈 - learn, grow, work, brainstorm ideas, contribute together so why not share about our weekly goals and the awesome work we have done at Public Lab with each other, so we can support and collaborate with each other better. We have a Community Check-In each week, where every community member can share something about their work from the past week and about their current week's goal 🎯 . You are also welcome to share fun-fact 😄 , new ideas 💡 , your learning goals ☑️.

We believe in collaborative efforts to support our community. We are running a learning platform which helps a newcomer to become a leader of tomorrow. 💯

## Share your adventures for the next few weeks and months

This week, it would be nice for us to share what our plans for the next few weeks are, especially after the summer projects.
For interns, it could be career goals, learning goals (maybe a few new stacks that you want to spend time to get good at) or college milestones or maybe a personal project you would like to embark on.

For mentors and others, it could be anything from how your work may change after the summer internships and other cool work and career related things you want to get doing. 

Hoping what we share inspires everyone else!😄 

### For interns 

Please also share issues you're working on that you need some help with.

### Thank you note to focus issues contributors

Thanks so much  @keshavsethi  for opening so many ftos  🥇 :1st_place_medal: 

## Next Check-in
If you would like to open the next check-in..Leave a comment below. We are happy to help if its your first time

**Thanks everyone for making Public Lab awesome** 🎈
Have a great week and year ahead all ❤️

**Comment by cesswairimu** [comment]
@jywarren, @AgyeyaMishra, @Jolios, @cesswairimu, @samarakoon-ryan, @Samasth, @malaikaaiyar, @keshavsethi, @OmLakshmi, @nsachin08, @dependabot-preview[bot], @Tlazypanda, @galanggg, @ishika1727, @icarito, @RajatSablok, @mronauli, @ijeomaemeruwa, @alaxalves, @Shulammite-Aso, @JapneetSingh5, @Neilblaze, @markkulube, @vinuch @JapneetSingh5, @Neilblaze, @markkulube, @vinuch, @Tlazypanda, @icarito, @dependabot-preview[bot], @jywarren, @keshavsethi, @praaatik, @Janitham97, @imanishbarnwal, @dburugupalli, @adityakpranav, @ioampatzidis, @esiebomaj, @Alexjake660, @cesswairimu, @urvashigupta7, @daemon1024, @jscastanos @keshavsethi, @jywarren, @AyanChoudhary, @imajit,@NitinBhasneria, @nstjean, @marientje, @rutger-t, @Janet33, @TroydonAnabolic, @priyanshbalyan, @Medlineme4, @mandysGit, @msanden, @AidenOliver, @Janetsomehow, @AntroMarina, @llabake, @khushi02, @Alexjake660, @LarrySul, @nicoleiocana, @chrisdrums1, @Angelvicks, @Akanksha1212, @beladinaelfitri, @rid1hady, @shreyaa-sharmaa, @goamoth, @SusannaDiV, @yusofsf, @nanlliu, @Tlazypanda,

**Comment by cesswairimu** [comment]
@llabake, @khushi02, @Alexjake660, @LarrySul, @nicoleiocana, @chrisdrums1, @Angelvicks, @Akanksha1212, @beladinaelfitri, @rid1hady, @shreyaa-sharmaa, @goamoth, @SusannaDiV, @yusofsf, @nanlliu, @Tlazypanda,@keshav234156, @WaldenJosh, @B4Lee, @VisnuGanth, @jessibreen, @alaxalves, @kamal-kaur04, @sssash18, @chinmay021, @Srija616, @AnnaMinakova, @greenbrown, @taysa91, @TaishiRoy, @yagmurbaydogan, @Shulammite-Aso, @Jigyasa-Kumari @moliver4, @justinelai, @Snouzy, @stevenalila, @Digiox, @yandu31, @milosv1, @jamescapps, @Nevenem, @chirag-wadhwa, @yogeshjdeshmukh, @omizrahi99, @theOpetunde, @sailahonkanen, @robin-natale, @avidler, @ccyccyccy
@urvashigupta7, @daemon1024, @Tlazypanda, @jscastanos, @sarthak-choudhary, @dongskyler, @keshavsethi, @Shulammite-Aso, @ckchu8, @keshav234156, @DerekChristy, @Srija616, @priyanka-choubey, @AyanChoudhary, @imajit, @NitinBhasneria, @nstjean, @marientje, @rutger-t,

**Comment by cesswairimu** [comment]
@Janet33, @TroydonAnabolic, @priyanshbalyan, @Medlineme4, @mandysGit, @msanden, @AidenOliver, @Janetsomehow, @AntroMarina, @llabake, @khushi02, @Alexjake660, @LarrySul, @nicoleiocana, @chrisdrums1, @Angelvicks, @Akanksha1212, @beladinaelfitri, @rid1hady, @shreyaa-s, @goamoth, @SusannaDiV, @yusofsf, @nanlliu, @WaldenJosh, @B4Lee, @VisnuGanth, @jessibreen, @alaxalves, @kamal-kaur04 @adityakpranav @esiebomaj @Yonttee @swarajpure @vinuch @ishika1727 @nsachin08 @Rohit-786 @daemon1024 @jscastanos, @sarthak-choudhary, @dongskyler, @keshavsethi, @Shulammite-Aso, @ckchu8, @keshav234156, @DerekChristy, @Srija616, @priyanka-choubey, @AyanChoudhary, @imajit, @NitinBhasneria, @nstjean, @marientje, @rutger-t,

**Comment by cesswairimu** [comment]
@jscastanos, @sarthak-choudhary, @dongskyler, @keshavsethi, @Shulammite-Aso, @ckchu8, @keshav234156, @DerekChristy, @Srija616, @priyanka-choubey, @AyanChoudhary, @imajit, @NitinBhasneria, @nstjean, @marientje, @rutger-t,  @imajit, @NitinBhasneria, @nstjean, @marientje, @rutger-t, @nsachin08 @Rohit-786 @Tristan-Elizabeth @aakanchha01 @habeckmatt @hiteshsubnani0128 @ijeomaemeruwa @OmLakshmi @dmoini @yusufatalay @Samasth @malaikaaiyar  @davidgoldcode @Shokescodes @marciojunior88 @avats-dev

**Comment by OmLakshmi** [comment]
Hello everyone!
I've been interning at a startup for the past month and it's been a ride. 
I'm currently working on a User Login Authentication using javascript and Django and would love some help since I'm totally new to Backend programming.

Have a great week✨

**Comment by Shulammite-Aso** [comment]
Hi all!😄 For me after the summer internship. I'm going to be applying for entry level to junior developer roles or internships as well. But I'm going to also be spending a lot of time learning and working with react and nodejs, as I'm very interested in becoming a full stack developer.  And of course I'll want to continue to contribute to publiclab, especially the editor repository.

Recently been trying to work on this https://github.com/publiclab/plots2/issues/8223 and figured out there is an [atwho_autocomplete.js](https://github.com/publiclab/plots2/blob/main/app/assets/javascripts/atwho_autocomplete.js) file, but 
 also saw it was only called on the comment editor. callled it on rich.html.erb file, but haven't seen it work on localhost.  I'm going to try out a few other things, but i'd also appreciate pointers if there are.  I should also mention that i installed At,js following the instructions here https://github.com/publiclab/PublicLab.Editor#atwhojs-data-module

**Comment by cesswairimu** [comment]
Hello all, 
 I am planning to do a cleanup across our repos for stale issues and 6months plus PRs, also fellow Rails Girls Nairobi organizers and I are planning to start organizing the meetups online late this month.
Great theme @Shulammite-Aso  :tada: 
Thanks @keshavsethi  for the ftos :tada: :tada:

**Comment by sagarpreet-chadha** [comment]
Hi everyone, 
I am planning to learn octokit client to use Github API's easily, other than that I will be reviewing PR's and try to track the status of PL editor team :smile:

Also, I want the PL editor team to volunteer for these unassigned tasks in the list here 💯 : 
https://github.com/publiclab/PublicLab.Editor/issues/490#issuecomment-668580733

Great check-in @Shulammite-Aso ! 
Thank you 🎈 🎉

**Comment by alaxalves** [comment]
Hey guyss, 

Since we have Rails 5 running on Spectral now, I'll focus on configuring and then implementing system tests and for the Export module I'll keep refactoring the huge methods we have there.

My plans for the next months are graduating :laughing: :laughing: :laughing: and get some time to travel after this pandemic is a little off. :)

**Comment by ebarry** [comment]
Hi all, I'm looking ahead at the Public Lab Open Hour in September where each and every Outreachy and Google Summer of Code participants @Shulammite-Aso @shreyaa-sharmaa @Tlazypanda @NitinBhasneria @keshav234156 @keshavsethi @alaxalves will share 5 minutes about their summer's work! Here's some considerations for this event: 

- Many of us are in UTC+4, UTC+5, so how about a start time of 8AM Pacific US West Coast to 8:30pm India Standard Time https://everytimezone.com/?t=5f28a500,384 ?
- if people have experienced difficulty in others hearing them on group video calls so far this year, consider recording a screencapture of your presentation ahead of time. 
- We will likely use Zoom because of its moderation features, but please share if you have other preferred and more stable video platforms for your region. 

Please share thoughts, thanks!

**Comment by jywarren** [comment]
Hi all! I'm looking ahead to my other gig wrapping up, which is a summer camp I'm teaching. It's fun but it's very exhausting, and my other work is getting a bit neglected. So I hope to take a few days of time off to rest. 

I realized that August is usually the time in the year when I find some time to take a vacation, but with the pandemic and everything it just didn't even occur to me. It's not like I'm going to go anywhere. But, maybe it means we should try to ride bikes to an isolated beach somewhere...  anyways, whether we get to take a "real" break or not, i'm looking forward to some cooler weather!

So cool to hear of all your plans and aspirations! 🎉 🎉

**Comment by Tlazypanda** [comment]
Hey everyone!

I have been mostly away this week with university but plan on taking some more performance improvements and finding an optimal way for printability :sweat_smile: 

For the months ahead I definitely plan to work more with Opensource :heart: and contribute!! I also dream that in a couple of months I will have some proficiency with Spanish lol :joy: I plan to learn more interesting stacks like elixir and clojure (maybe @cesswairimu can guide me :sweat_smile: ) I am still in university so don't have any major career plans for now (btw can you actually work with Opensource as an engineer if yes how do you apply or what qualifications do they require sorry too many questions :joy: ) 

@ebarry  The time and zoom sounds fine by me :v: I also think the prerecord idea is great because with my connection atleast its quite possible to drop off anytime outta nowhere :sweat_smile:

**Comment by shreyaa-sharmaa** [comment]
Hey everyone!

For the next week, I'll devote more time to the Editor.
For the coming months I wish to learn golang, ruby and flutter. I also want to learn more about cybersecurity and then try out CTFs, so that's definitely first on the list after summer internship.

Insipred by @Tlazypanda I've started brushing up on my french that I learned in school. Turns out I remember more than I thought I did. :laughing: 

Can't wait to go out :cry: 
Time and zoom works for me! :tada: :tada:

**Comment by Shulammite-Aso** [comment]
> Hi all, I'm looking ahead at the Public Lab Open Hour in September where each and every Outreachy and Google Summer of Code participants @Shulammite-Aso @shreyaa-sharmaa @Tlazypanda @NitinBhasneria @keshav234156 @keshavsethi @alaxalves will share 5 minutes about their summer's work! Here's some considerations for this event:
> 
> * Many of us are in UTC+4, UTC+5, so how about a start time of 8AM Pacific US West Coast to 8:30pm India Standard Time https://everytimezone.com/?t=5f28a500,384 ?
> * if people have experienced difficulty in others hearing them on group video calls so far this year, consider recording a screencapture of your presentation ahead of time.
> * We will likely use Zoom because of its moderation features, but please share if you have other preferred and more stable video platforms for your region.
> 
> Please share thoughts, thanks!

I think zoom and prerecording will be cool. Only that Tuesdays between 3:30pm - 6pm WAT is usually busy for me, saying this because the meeting may be scheduled for Tuesday and 8AM Pacific US West Coast will be 4pm my local time. Will the meeting likely be on a tuesday?

**Comment by jywarren** [comment]
> (btw can you actually work with Opensource as an engineer if yes how do you apply or what qualifications do they require sorry too many questions 😂 )

Yes, you can! Lots of companies use lots of open source. MapBox is one i can think of right off that does it very transparently! But many companies big and small. After all, Bootstrap is by Twitter, and Rails is by a commercial company too. 🎉

**Comment by cesswairimu** [comment]
Thanks everyone for sharing this was a great one ...Anyone willing to open this week's check-in?

**Comment by cesswairimu** [comment]
Moved to https://github.com/publiclab/plots2/issues/8280. Thanks everyone
