### ISSUE TITLE
Add a button that allows the user to insert a block of code in Rich Editor

### ISSUE THREAD

**Issue by klie1** [publiclab/PublicLab.Editor#85]
For example: In the legacy editor, it is possible to just copy/paste code... and when it's published, you see the "reader friendly" view of it.  For example, that's how I created [this note](https://publiclab.org/notes/klie/12-21-2016/public-lab-community-newsletter-december-2016).

In the new editor, the code disappears after you enter it.

Also, I am not a coder and therefore don't know the technical terms for anything, so let me know if you have questions!

**Comment by jywarren** [comment]
I can help with code pointers and stuff on this -- this feature could be much like the "add Table" button, which is implemented here:

https://github.com/publiclab/PublicLab.Editor/blob/master/src/modules/PublicLab.RichTextModule.Table.js#L55-L95

![screen shot 2017-01-10 at 5 38 49 pm](https://cloud.githubusercontent.com/assets/24359/21827900/ad2b2046-d75b-11e6-9fd8-f4a58ba72645.png)

the things you're looking for are, in markdown, called "code fences", and use three "`" characters, on their own line, before and after the content. 

The key sections are this, for adding a new button with a unique classname:

```js
  $('.wk-commands').append('<a class="woofmark-command-code-fences btn btn-default"><i class="fa fa-table"></i></a>');
```

and this, for running the command which adds in the new content at the insertion point:

```js
$('.ple-table-size').click(function() {
  wysiwyg.runCommand(function(chunks, mode) {
      chunks.before += _module.wysiwyg.parseMarkdown("\n```\n"); // newlines before and after
      chunks.after += _module.wysiwyg.parseMarkdown("\n```\n");
      _module.afterParse(); // tell editor we're done here
  });
});
```

We'd want to select an appropriate icon from FontAwesome, too, instead of `fa-table`, as in the above code snippet: 

https://fontawesome.io/icons/

I think it makes sense for this to be its own module, like `PublicLab.RichTextModule.Table.js` is, so, `PublicLab.RichTextModule.CodeFences.js`

And we'd include and initialize it here, just like we do for the Table sub-module: 

https://github.com/publiclab/PublicLab.Editor/blob/e5e0ac69ac5e8f3f14b7664817030c916201b928/src/adapters/PublicLab.Woofmark.js#L238

Happy to chip in extra help if someone wants to add this feature!

**Comment by djmgit** [comment]
@jywarren  I am working on this.

I have created a new module named PublicLab.RichTextModule.CodeFences which contains the following :

```
module.exports = function initCodeFences(_module, wysiwyg) {

  // create a menu option for codefence
  $('.wk-commands').append('<a class="woofmark-command-code-fences btn btn-default"><i class="fa fa-table"></i></a>');

  $('.wk-commands .woofmark-command-code-fences').click(function() {

    wysiwyg.runCommand(function(chunks, mode) {

      chunks.before += _module.wysiwyg.parseMarkdown("\n```\n"); // newlines before and after
      chunks.after += _module.wysiwyg.parseMarkdown("\n```\n");
      module.afterParse(); // tell editor we're done here
    });
 });
}

```

and I have initialized it in Public.Woofmark.js :

```
require('../modules/PublicLab.RichTextModule.CodeFences.js')(_module, wysiwyg);

```

grunt build is showing no error, new button is getting added however it is not functioning as desired.
``` is not getting inserted

**Comment by jywarren** [comment]
Hi, can you open a pull request with your code so I can take a look? 

Have you confirmed that the new module is being included in? See how that's done here: https://github.com/publiclab/PublicLab.Editor/blob/master/src/PublicLab.Editor.js#L22

I think we could write a test to ensure this, like this: https://github.com/publiclab/PublicLab.Editor/blob/master/spec/javascripts/tags_module_spec.js

I'm happy to help you figure out how to do these things as well; it's easiest if I can look at your code so far in a PR. Thank you!!!

**Comment by djmgit** [comment]
@jywarren I will send a PR soon :)

**Comment by jywarren** [comment]
Hi, I've realized that there is already a feature to do code blocks, the fourth button from the left. But I've requested that @djmgit adapt his excellent work to solve #88, which will require almost identical code, but for horizontal rules, like:

****

I'm closing this issue as a result, and the new pull request #92 will apply to #88 instead of this. Thank you and apologies!
